/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'interview' : IDL.Null,
  'cinema' : IDL.Null,
  'viralNews' : IDL.Null,
  'politics' : IDL.Null,
});
export const AuthorInfo = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
export const Time = IDL.Int;
export const NewsArticle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Time,
  'author' : AuthorInfo,
  'excerpt' : IDL.Text,
  'category' : Category,
  'imageId' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        Category,
        AuthorInfo,
      ],
      [],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Text], [], []),
  'getAllArticles' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getArticleById' : IDL.Func([IDL.Text], [NewsArticle], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCategoriesInHindi' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        Category,
        AuthorInfo,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'interview' : IDL.Null,
    'cinema' : IDL.Null,
    'viralNews' : IDL.Null,
    'politics' : IDL.Null,
  });
  const AuthorInfo = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const NewsArticle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Time,
    'author' : AuthorInfo,
    'excerpt' : IDL.Text,
    'category' : Category,
    'imageId' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          Category,
          AuthorInfo,
        ],
        [],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Text], [], []),
    'getAllArticles' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getArticleById' : IDL.Func([IDL.Text], [NewsArticle], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCategoriesInHindi' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          Category,
          AuthorInfo,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };